sudo: required
services:
  - docker

before_install:
  - docker build -t geneiryodan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true geneiryodan/docker-react npm run test -- --coverage