sudo: required
services:
  - docker

before_install:
  - docker build -t geneiryodan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true geneiryodan/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-852594683946"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY